export const pickuplines = [
  "Você é uma câmera? Porque cada vez que olho para você, sorrio.",
  "Se beleza fosse tempo, você seria a eternidade.",
  "Você é um Wi-Fi? Porque estou sentindo uma conexão.",
  "Você acredita em amor à primeira vista, ou devo passar por aqui novamente?",
  "Você não é um dicionário, mas você adiciona significado à minha vida.",
  "Se você fosse uma estrela, seria uma estrela cadente, porque você ilumina meu céu.",
  "Você é um ladrão? Porque roubou meu coração.",
  "Se você fosse uma fruta, seria uma uva, porque é impossível não ficar vinho com você.",
  "Você não é Google, mas tem tudo o que tenho procurado.",
  "Se você fosse uma pizza, você seria a melhor parte, a borda.",
  "Você é fã de astrologia? Porque quando nos encontramos, foi uma constelação.",
  "Se beleza fosse crime, você estaria cumprindo prisão perpétua.",
  "Você é o que acontece quando a beleza encontra o senso de humor.",
  "Você é uma câmera digital? Porque cada vez que sorrio, você me captura.",
  "Você é a causadora do aquecimento global, porque está ficando quente aqui.",
  "Você gosta de jardins? Porque eu realmente estou sentindo uma conexão crescente entre nós.",
  "Se você fosse um sanduíche, você seria um sanduíche perfeito, porque tem tudo o que eu quero.",
  "Você é feito de cobre e telúrio? Porque você é Cu-Te.",
  "Você é uma bússola? Porque sem você, eu estou perdido.",
  "Você é um controlador de tráfego? Porque parou meu coração.",
  "Você não é o sol, mas você é a única coisa que ilumina meu dia.",
  "Se você fosse um vírus, seria o melhor tipo de vírus, porque você contagiaria meu coração.",
  "Você acredita em amor à segunda vista, ou devo passar novamente?",
  "Se beleza fosse dinheiro, você seria uma fortuna.",
  "Você não é um mapa, mas você é a direção certa.",
  "Se você fosse uma música, seria a melodia perfeita.",
  "Você é uma lanterna? Porque ilumina minha vida.",
  "Você é um gato? Porque você acabou de arranhar meu coração.",
  "Você é uma piada? Porque sempre me faz sorrir.",
  "Você gosta de café? Porque você está moendo meu coração.",
  "Você não é um quebra-cabeça, mas você completa a minha vida.",
  "Você é uma colher? Porque você está mexendo meu coração.",
  "Se você fosse um aplicativo, seria o meu favorito.",
  "Você é uma estrela do mar? Porque você é maravilhosa de ponta a ponta.",
  "Você é um terremoto? Porque você sacudiu meu mundo.",
  "Você é uma abelha? Porque você está fazendo meu coração zumbir.",
  "Você é uma vela? Porque você está iluminando meu caminho.",
  "Você gosta de nadar? Porque você está fazendo meu coração mergulhar.",
  "Você é um espelho? Porque vejo meu futuro nele.",
  "Você é uma bateria? Porque você está energizando meu dia.",
  "Você é uma caixa de cereal? Porque você é deliciosa.",
  "Você é um cartão de crédito? Porque você tem tudo o que eu quero.",
  "Você é uma abóbora? Porque você é irresistível.",
  "Você é um livro? Porque eu não consigo parar de ler sobre você.",
  "Você é uma escada? Porque você está me levando para as alturas.",
  "Você é um sapato? Porque você se encaixa perfeitamente na minha vida.",
  "Você é uma nuvem? Porque você faz meu dia ficar mais brilhante.",
  "Você é um refrigerante? Porque você é a coisa mais refrescante que eu já vi.",
  "Você é uma chave inglesa? Porque você aperta meu coração.",
  "Você é uma previsão do tempo? Porque você está prevendo uma chuva de amor.",
  "Você é uma impressora? Porque quando estou contigo, meu coração está imprimindo amor.",
  "Se você fosse uma fruta, seria uma abacaxi. Porque você é de dar um nó na língua.",
  "Você é um controle remoto? Porque você está mudando os canais do meu coração.",
  "Se você fosse um sanduíche, você seria um 'sanduiche-iche'. Porque você é demais.",
  "Você é uma pergunta difícil em um jogo de trivia, porque eu nunca quero pular essa questão.",
  "Você é um carregador de celular? Porque sem você, minha vida fica sem energia.",
  "Você é um café? Porque você me mantém acordado à noite.",
  "Se você fosse uma pizza, você seria uma pizza com borda recheada de boas intenções.",
  "Você é uma aula de matemática? Porque você me deixa confuso, mas eu gosto disso.",
  "Você é uma caixa de cereal? Porque eu não consigo parar de ler as suas qualidades.",
  "Se você fosse uma planta, seria uma bromélia. Porque você é exótica e cheia de vida.",
  "Você é um feriado? Porque estar com você é sempre um momento especial.",
  "Você é uma notificação do celular? Porque eu sempre quero ver o que você tem a dizer.",
  "Você é um código de barras? Porque eu não consigo decifrar o quanto você é incrível.",
  "Se você fosse uma vela, seria aquela que ilumina toda a festa.",
  "Você é um emoji? Porque sempre que penso em você, meu rosto fica com um sorriso.",
  "Você é um quebra-cabeça? Porque eu estou perdido sem você.",
  "Você é uma escova de dentes? Porque eu não quero começar o dia sem você.",
  "Se você fosse uma música, seria a trilha sonora da minha felicidade.",
  "Você é um furacão? Porque você trouxe uma reviravolta na minha vida.",
  "Você é um quadro? Porque eu não consigo tirar os olhos de você.",
  "Você é uma chave? Porque você abre as portas do meu coração.",
  "Se você fosse um filme, seria uma comédia romântica, porque você faz meu coração rir.",
  "Você é um sinal de trânsito? Porque eu não consigo parar de olhar para você.",
  "Você é um raio de sol? Porque você ilumina até os dias mais nublados.",
  "Você é uma varinha mágica? Porque cada vez que te vejo, coisas mágicas acontecem.",
  "Se você fosse uma estação do ano, seria o verão. Porque contigo, tudo fica mais quente.",
  "Você é um botão? Porque você aciona os sentimentos mais incríveis em mim.",
  "Você é um lápis? Porque você colore minha vida.",
  "Se você fosse um livro, seria o meu livro de cabeceira.",
  "Você é um arco-íris? Porque você colore os dias cinzentos.",
  "Você é um cometa? Porque você ilumina meu céu mesmo em rápida passagem.",
  "Se você fosse uma carta, seria a carta mais valiosa do meu baralho.",
  "Você é uma piada de knock-knock? Porque quando estou com você, tudo fica mais leve.",
  "Você é uma máquina de fliperama? Porque você faz o meu coração pular de alegria.",
  "Se você fosse uma nuvem, seria a nuvem nove. Porque estar com você é celestial.",
  "Você é um GPS? Porque eu não consigo me perder em seus olhos.",
  "Você é uma xícara de chá? Porque você aquece meu coração.",
  "Se você fosse um parque de diversões, seria o meu parque favorito.",
  "Você é um emoji de coração? Porque você é a expressão máxima do meu afeto.",
  "Você é um dom? Porque você é algo que eu nunca soube que precisava.",
  "Se você fosse um filme de terror, seria aquele que me faz gritar de felicidade.",
  "Você é uma chave de fenda? Porque você aperta meu amor até o máximo.",
  "Você é um sinal de exclamação? Porque você sempre deixa minha vida emocionante!",
  "Se você fosse uma receita, seria a receita para a minha felicidade.",
  "Você é uma pilha? Porque você dá energia à minha vida.",
  "Você é um jogo de tabuleiro? Porque com você, cada momento é uma jogada estratégica.",
  "Se você fosse uma fruta, seria uma manga. Porque você é 'mangavaliosa'!",
  "Você é um terremoto? Porque você faz meu mundo tremer.",
  "Você é um sinal de adição? Porque com você, tudo soma.",
  "Você é um arquivo compactado? Porque meu coração se aperta quando estou perto de você.",
  "Se você fosse uma pizza, seria uma pizza de queijo. Porque você é 'gouda' demais!",
  "Você é um navegador de internet? Porque quando estou contigo, sempre entro em 'modo privado'.",
  "Você gosta de estrelas cadentes? Porque eu desejo você toda noite.",
  "Você é uma abelha? Porque você faz meu coração zumbir de felicidade.",
  "Você é um piquenique? Porque sempre que penso em você, meu coração faz um 'lanchinho'.",
  "Se você fosse um elemento, seria 'Be'. Porque você é 'beryllium'!",
  "Você é um erro de sistema? Porque você bagunça com a minha lógica.",
  "Você gosta de nadar? Porque você está fazendo meu coração mergulhar de amor.",
  "Se beleza fosse tempo, você seria a eternidade. E eu ficaria perdido nela para sempre.",
  "Você é um farol? Porque você ilumina o meu caminho na escuridão.",
  "Você é um diamante? Porque você é valioso e brilha mais do que qualquer outra coisa.",
  "Você é um botão de pause? Porque cada vez que te vejo, o mundo para ao meu redor.",
  "Você é um feixe de luz? Porque você ilumina até os dias mais sombrios.",
  "Se você fosse uma planta, seria um cacto. Porque você é raro e irresistível.",
  "Você é um sinal de interrogação? Porque quando penso em você, todas as perguntas desaparecem.",
  "Você é uma folha de outono? Porque você colore minha vida com tons de felicidade.",
  "Você é um livro de piadas? Porque você sempre me faz rir.",
  "Você é um travesseiro? Porque eu só quero abraçar você todas as noites.",
  "Você é uma caneta? Porque você assina a sua presença no meu coração.",
  "Você é uma tela em branco? Porque eu mal posso esperar para pintar memórias incríveis contigo.",
  "Você é uma caneca? Porque você é a bebida perfeita para alegrar meu dia.",
  "Se você fosse um planetário, seria o meu céu estrelado favorito.",
  "Você é uma piñata? Porque meu coração quer te dar uma batidinha.",
  "Você é um código QR? Porque quando eu escaneio você, só recebo amor em retorno.",
  "Se você fosse uma estação de rádio, seria a minha música favorita.",
  "Você é um lenço? Porque você enxuga as lágrimas e aquece meu coração.",
  "Você é uma lanterna mágica? Porque você projeta sonhos incríveis na minha vida.",
  "Se você fosse uma bolsa, seria a bolsa do tesouro. Porque você é valioso demais.",
  "Você é um poema? Porque cada palavra sua é uma poesia para os meus ouvidos.",
  "Você é um cartão postal? Porque você representa lugares lindos e momentos especiais.",
  "Você é uma cereja? Porque você é a cereja do bolo da minha felicidade.",
  "Se você fosse uma batata frita, seria aquela que eu não consigo parar de comer.",
  "Você é uma nota musical? Porque você é a melodia perfeita na sinfonia da minha vida.",
  "Você é uma canção de ninar? Porque sua presença acalma o meu coração.",
  "Você é uma câmera instantânea? Porque com você, todos os momentos são especiais e capturados.",
  "Se você fosse um jogo de tabuleiro, seria o meu favorito. Porque cada jogada contigo é uma vitória.",
  "Você é um livro de receitas? Porque a vida contigo é uma mistura perfeita de sabores.",
  "Você é um botão de repetição? Porque eu só quero viver esses momentos incríveis contigo de novo e de novo.",
  "Você é um foguete? Porque quando estou com você, sinto como se estivéssemos no espaço.",
  "Você é uma rosa? Porque, assim como uma rosa, você é bela e perfuma a minha vida.",
  "Você é um controle de volume? Porque você faz o som da minha felicidade ficar mais alto.",
  "Se você fosse uma palavra cruzada, eu escolheria você como a resposta para todas as pistas.",
  "Você é uma máquina de sorvete? Porque a vida contigo é sempre doce e refrescante.",
  "Você é um controle remoto? Porque eu mal posso esperar para te apertar.",
  "Se você fosse um número, seria o meu número da sorte.",
  "Você é um aplicativo? Porque você faz o meu coração 'crashar'.",
  "Você gosta de astronomia? Porque quando eu te vejo, as estrelas se alinham.",
  "Você é uma abelha rainha? Porque você é a única que reina no meu coração.",
  "Você é uma câmera GoPro? Porque tudo que vejo é mais emocionante contigo.",
  "Se você fosse um planeta, seria o Planeta Felicidade, orbitando ao redor do meu coração.",
  "Você é um cobertor? Porque quando estou com você, me sinto confortável e aquecido.",
  "Você é uma escada? Porque cada vez que te vejo, sinto que estou subindo na vida.",
  "Se você fosse uma flor, seria um girassol. Sempre seguindo a luz do meu sorriso.",
  "Você é um ímã? Porque sempre somos atraídos um pelo outro.",
  "Você é um pacote de biscoitos? Porque você é delicioso e impossível de resistir.",
  "Você é um controle de videogame? Porque com você, cada momento é uma aventura.",
  "Se você fosse uma vela aromática, seria a vela que deixa a vida mais perfumada.",
  "Você é um dia de folga? Porque tudo fica melhor quando estou com você.",
  "Você é um foguete? Porque quando estamos juntos, sinto como se estivéssemos nas estrelas.",
  "Você é um dia ensolarado? Porque você ilumina até os dias mais nublados.",
  "Se você fosse um super-herói, seria 'Amoroso'.",
  "Você é um quebra-cabeça? Porque eu só estou completo quando estou com você.",
  "Você é um pote de ouro? Porque encontrar você é como encontrar um tesouro.",
  "Você é um emoji de coração? Porque você é a expressão máxima do meu afeto.",
  "Você é um relógio? Porque o tempo para quando estou com você.",
  "Você é uma onda do mar? Porque você me envolve e me leva para longe.",
  "Se você fosse um sorriso, seria o meu sorriso favorito.",
  "Você é uma playlist? Porque cada música contigo é a minha favorita.",
  "Você é um queijo? Porque você faz qualquer situação ficar 'grate'.",
  "Você é um abraço? Porque tudo fica melhor quando estou nos seus braços.",
  "Se você fosse uma fruta, seria uma banana. Porque você é a casca da minha felicidade.",
  "Você é um pássaro? Porque meu coração canta quando você está por perto.",
  "Você é uma janela? Porque sempre que olho para você, vejo um futuro brilhante.",
  "Você é um chapéu? Porque você adiciona estilo à minha vida.",
  "Se você fosse um instrumento musical, seria um tambor. Porque você faz meu coração bater mais rápido.",
  "Você é um arco-íris duplo? Porque com você, a vida é ainda mais colorida.",
  "Você é uma festa surpresa? Porque cada momento contigo é uma surpresa maravilhosa.",
  "Você é uma nuvem fofa? Porque você faz o meu dia mais leve.",
  "Você é um raio de sol? Porque você ilumina até as partes mais escuras da minha vida.",
  "Se você fosse uma piada, seria a piada que nunca fica velha.",
  "Você é um poema de amor? Porque suas palavras são a melodia do meu coração.",
  "Você é um diamante bruto? Porque você é precioso e ainda está se revelando.",
  "Você é um troféu? Porque você é a conquista mais valiosa da minha vida.",
  "Você é um raio? Porque você é chocante de tão incrível.",
  "Você é um sapato? Porque com você, eu dou passos firmes na direção da felicidade.",
  "Você é uma máquina de sorvete? Porque a vida contigo é sempre doce e refrescante.",
  "Você é uma risada? Porque você alegra até os dias mais cinzentos.",
  "Se você fosse um filme, seria uma comédia romântica. Porque você faz minha vida mais leve.",
  "Você é uma montanha-russa? Porque estar com você é uma aventura emocionante.",
  "Você é um ar condicionado? Porque você deixa meu coração sempre fresquinho.",
  "Você é um jogo de quebra-cabeça? Porque você completa todas as peças da minha vida.",
  "Se você fosse uma tela em branco, eu escolheria pintar o nosso futuro juntos.",
  "Você é uma playlist? Porque cada música contigo é uma melodia única.",
  "Você é um jardim secreto? Porque desvendar você é a melhor descoberta.",
  "Você é uma chave? Porque você abre os caminhos do meu coração.",
  "Você é um cometa? Porque você ilumina o céu da minha vida em passagem rápida.",
  "Você é um joguinho de celular? Porque eu não consigo parar de jogar na sua atenção.",
  "Você é uma piñata? Porque meu coração quer te dar uma batidinha.",
  "Você é um botão de repetição? Porque eu só quero viver esses momentos incríveis contigo de novo e de novo.",
  "Você é um foguete? Porque quando estou com você, sinto como se estivéssemos no espaço.",
  "Você é uma rosa? Porque, assim como uma rosa, você é bela e perfuma a minha vida.",
  "Você é um controle de volume? Porque você faz o som da minha felicidade ficar mais alto.",
  "Se você fosse uma palavra cruzada, eu escolheria você como a resposta para todas as pistas.",
  "Você é uma máquina de sorvete? Porque a vida contigo é sempre doce e refrescante.",
  "Você é um farol na escuridão do meu dia.",
  "Se você fosse um livro, seria o meu best-seller.",
  "Você é um ímã de felicidade, porque tudo parece ser atraído para você.",
  "Você é uma estrela cadente? Porque eu desejo que você fique comigo para sempre.",
  "Você é uma semente de girassol? Porque você sempre segue a luz do meu sorriso.",
  "Se você fosse um jogo, seria esconde-esconde, porque eu sempre me perco em seus olhos.",
  "Você é um arco-íris? Porque você colore o meu mundo.",
  "Você é uma tela em branco? Porque com você, cada momento é uma obra de arte.",
  "Você é um atalho do teclado? Porque você simplifica a complexidade da vida.",
  "Se você fosse um filme, seria uma comédia romântica, porque você é a risada da minha vida.",
  "Você é um sonho de infância? Porque eu nunca quero acordar.",
  "Você é uma constelação? Porque você dá brilho às noites mais escuras.",
  "Se beleza fosse crime, você estaria preso pela eternidade.",
  "Você é um cartão postal? Porque com você, cada momento é digno de ser lembrado.",
  "Você é uma colher? Porque você mexe meu coração.",
  "Você é um botão de volume? Porque com você, a vida fica mais alta e intensa.",
  "Se você fosse uma fruta, seria uma amora. Porque você é 'amora'viosa.",
  "Você é uma seta? Porque você direciona o caminho para a minha felicidade.",
  "Você é um filtro do Instagram? Porque você torna cada momento mais bonito.",
  "Você é uma lâmpada? Porque você ilumina o meu caminho.",
  "Se você fosse uma estação do ano, seria a primavera. Porque você traz flores para a minha vida.",
  "Você é uma receita secreta? Porque com você, tudo fica mais saboroso.",
  "Você é uma borboleta? Porque você faz meu estômago sentir borboletas.",
  "Se você fosse um sentimento, seria a alegria. Porque você me faz feliz.",
  "Você é um abridor de portas? Porque você abriu as portas do meu coração.",
  "Você é um escudo? Porque você me protege de todos os males.",
  "Você é uma sinfonia? Porque com você, cada momento é uma melodia única.",
  "Se você fosse uma moeda, seria rara e valiosa.",
  "Você é um código QR? Porque eu não consigo decifrar o quanto você é incrível.",
  "Você é um bolo de aniversário? Porque com você, cada dia é especial.",
  "Você é um cobertor elétrico? Porque você me mantém aquecido durante as noites frias.",
  "Se você fosse uma onda, seria uma onda de felicidade.",
  "Você é um quebra-cabeça complicado? Porque eu não consigo parar de tentar te entender.",
  "Você é um despertador? Porque você acorda a felicidade em mim.",
  "Você é um parque de diversões? Porque estar com você é sempre uma aventura emocionante.",
  "Se você fosse uma nuvem, seria uma nuvem de algodão. Porque você é suave e doce.",
  "Você é um cupcake? Porque você é uma delícia em todas as camadas.",
  "Você é uma luz no fim do túnel? Porque você guia o caminho para a felicidade.",
  "Se você fosse um livro de receitas, seria o meu guia para a vida.",
  "Você é um GPS? Porque você me ajuda a encontrar o caminho para o seu coração.",
  "Você é um queijo? Porque você é maduro e envelhecendo bem.",
  "Você é um café expresso? Porque você dá um 'boost' à minha vida.",
  "Você é um planeta? Porque você é o centro do meu universo.",
  "Se você fosse um livro de piadas, seria o meu favorito.",
  "Você é um super-herói? Porque você salva o meu dia sempre que está por perto.",
  "Você é uma máquina do tempo? Porque com você, o tempo voa.",
  "Se você fosse um jardim, seria o jardim da minha alegria.",
  "Você é um livro de contos de fadas? Porque com você, cada dia é um conto mágico.",
  "Você é um par de óculos? Porque você me faz ver o mundo de maneira diferente.",
  "Você é uma estação de rádio? Porque com você, a sintonia é perfeita.",
  "Se você fosse um animal, seria um gatinho. Porque você é fofo e sempre faz meu coração miar.",
  "Você é um feriado? Porque com você, cada dia é uma celebração.",
  "Você é um amplificador? Porque com você, o amor fica mais alto.",
  "Se você fosse um pássaro, seria uma andorinha. Porque você voa diretamente para o meu coração.",
  "Você é um piquenique? Porque tudo fica melhor quando estou com você.",
  "Você é uma aurora boreal? Porque você pinta o céu da minha vida com cores incríveis.",
  "Se você fosse um avião, seria o meu voo favorito.",
  "Você é um emoji de coração? Porque você é a expressão máxima do meu afeto.",
  "Você é uma xícara de chá? Porque você aquece meu coração.",
  "Você é um abraço? Porque com você, tudo fica mais acolhedor.",
  "Se você fosse um tesouro, seria o meu maior achado.",
  "Você é uma playlist? Porque com você, a música da minha vida é perfeita.",
  "Você é um arco-íris duplo? Porque com você, a vida é ainda mais colorida.",
  "Você é uma estrela-guia? Porque você me leva aos caminhos certos.",
  "Se você fosse uma chave, abriria as portas da minha felicidade.",
  "Você é um jogo de tabuleiro? Porque cada momento contigo é uma jogada estratégica.",
  "Você é uma máquina de algodão doce? Porque você adoça a minha vida.",
  "Se você fosse um bolo, seria o meu favorito, porque cada pedaço é uma delícia.",
  "Você é uma vela aromática? Porque você faz cada momento mais especial.",
  "Você é um instrumento musical? Porque você toca as notas mais doces do meu coração.",
  "Se você fosse uma nuvem, seria aquela nuvem fofa que me faz sorrir.",
  "Você é um jogo de videogame? Porque eu não consigo parar de jogar na sua atenção.",
  "Você é um sorriso? Porque cada vez que você sorri, meu dia fica mais brilhante.",
  "Se você fosse uma árvore, seria a árvore da minha vida.",
  "Você é um botão de repetição? Porque eu só quero viver esses momentos incríveis contigo de novo e de novo.",
  "Você é um foguete? Porque quando estou com você, sinto como se estivéssemos no espaço.",
  "Você é uma rosa? Porque, assim como uma rosa, você é bela e perfuma a minha vida.",
  "Você é um controle de volume? Porque você faz o som da minha felicidade ficar mais alto.",
  "Se você fosse uma palavra cruzada, eu escolheria você como a resposta para todas as pistas.",
  "Você é uma máquina de sorvete? Porque a vida contigo é sempre doce e refrescante."
]